### ISSUE TITLE
Error while started to train on colab

### ISSUE THREAD

**Issue by E-B-Manohar** [savya08/Image-Captioning#1]
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-49-e73bb9b6450a> in <module>()
      1 max_len = maximum_length(captions)
----> 2 history = train(train_captions, train_images, word_to_index, max_len)

11 frames
<ipython-input-41-90339ce7b30b> in train(train_captions, train_images, word_to_index, max_length, num_epochs, batch_size)
      3   for epoch in range(num_epochs):
      4     generator = data_generator(train_captions, train_images, word_to_index, max_length, batch_size)
----> 5     history = model.fit_generator(generator, epochs = 1, steps_per_epoch = len(train_captions) // batch_size, verbose = 1)
      6     model.save('/content/Image-Captioning/Model_Weights/model_weights_' + str(epoch) + '.h5')
      7   return history

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1859         use_multiprocessing=use_multiprocessing,
   1860         shuffle=shuffle,
-> 1861         initial_epoch=initial_epoch)
   1862 
   1863   def evaluate_generator(self,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1098                 _r=1):
   1099               callbacks.on_train_batch_begin(step)
-> 1100               tmp_logs = self.train_function(iterator)
   1101               if data_handler.should_sync:
   1102                 context.async_wait()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    826     tracing_count = self.experimental_get_tracing_count()
    827     with trace.Trace(self._name) as tm:
--> 828       result = self._call(*args, **kwds)
    829       compiler = "xla" if self._experimental_compile else "nonXla"
    830       new_tracing_count = self.experimental_get_tracing_count()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    860       # In this case we have not created variables on the first call. So we can
    861       # run the first trace but we should fail if variables are created.
--> 862       results = self._stateful_fn(*args, **kwds)
    863       if self._created_variables:
    864         raise ValueError("Creating variables on a non-first call to a function"

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2939     with self._lock:
   2940       (graph_function,
-> 2941        filtered_flat_args) = self._maybe_define_function(args, kwargs)
   2942     return graph_function._call_flat(
   2943         filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3356               call_context_key in self._function_cache.missed):
   3357             return self._define_function_with_shape_relaxation(
-> 3358                 args, kwargs, flat_args, filtered_flat_args, cache_key_context)
   3359 
   3360           self._function_cache.missed.add(call_context_key)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _define_function_with_shape_relaxation(self, args, kwargs, flat_args, filtered_flat_args, cache_key_context)
   3278 
   3279     graph_function = self._create_graph_function(
-> 3280         args, kwargs, override_flat_arg_shapes=relaxed_arg_shapes)
   3281     self._function_cache.arg_relaxed[rank_only_cache_key] = graph_function
   3282 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3204             arg_names=arg_names,
   3205             override_flat_arg_shapes=override_flat_arg_shapes,
-> 3206             capture_by_value=self._capture_by_value),
   3207         self._function_attributes,
   3208         function_spec=self.function_spec,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    988         _, original_func = tf_decorator.unwrap(python_func)
    989 
--> 990       func_outputs = python_func(*func_args, **func_kwargs)
    991 
    992       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    632             xla_context.Exit()
    633         else:
--> 634           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    635         return out
    636 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    975           except Exception as e:  # pylint:disable=broad-except
    976             if hasattr(e, "ag_error_metadata"):
--> 977               raise e.ag_error_metadata.to_exception(e)
    978             else:
    979               raise

ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:754 train_step
        y_pred = self(x, training=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_spec.py:207 assert_input_compatibility
        ' input tensors. Inputs received: ' + str(inputs))

    ValueError: Layer model_1 expects 2 input(s), but it received 3 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, None) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, None) dtype=int32>, <tf.Tensor 'IteratorGetNext:2' shape=(None, None) dtype=float32>]

https://colab.research.google.com/drive/1EMV841olelsbeMixPrqO0xYWkoLkPpGR?usp=sharing

**Comment by E-B-Manohar** [comment]
> ## /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
> warnings.warn('`Model.fit_generator` is deprecated and '
> ValueError Traceback (most recent call last)
> in ()
> 1 max_len = maximum_length(captions)
> ----> 2 history = train(train_captions, train_images, word_to_index, max_len)
> 
> 11 frames
> in train(train_captions, train_images, word_to_index, max_length, num_epochs, batch_size)
> 3 for epoch in range(num_epochs):
> 4 generator = data_generator(train_captions, train_images, word_to_index, max_length, batch_size)
> ----> 5 history = model.fit_generator(generator, epochs = 1, steps_per_epoch = len(train_captions) // batch_size, verbose = 1)
> 6 model.save('/content/Image-Captioning/Model_Weights/model_weights_' + str(epoch) + '.h5')
> 7 return history
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
> 1859 use_multiprocessing=use_multiprocessing,
> 1860 shuffle=shuffle,
> -> 1861 initial_epoch=initial_epoch)
> 1862
> 1863 def evaluate_generator(self,
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
> 1098 _r=1):
> 1099 callbacks.on_train_batch_begin(step)
> -> 1100 tmp_logs = self.train_function(iterator)
> 1101 if data_handler.should_sync:
> 1102 context.async_wait()
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in **call**(self, *args, **kwds)
> 826 tracing_count = self.experimental_get_tracing_count()
> 827 with trace.Trace(self._name) as tm:
> --> 828 result = self._call(*args, **kwds)
> 829 compiler = "xla" if self._experimental_compile else "nonXla"
> 830 new_tracing_count = self.experimental_get_tracing_count()
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
> 860 # In this case we have not created variables on the first call. So we can
> 861 # run the first trace but we should fail if variables are created.
> --> 862 results = self._stateful_fn(*args, **kwds)
> 863 if self._created_variables:
> 864 raise ValueError("Creating variables on a non-first call to a function"
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in **call**(self, *args, **kwargs)
> 2939 with self._lock:
> 2940 (graph_function,
> -> 2941 filtered_flat_args) = self._maybe_define_function(args, kwargs)
> 2942 return graph_function._call_flat(
> 2943 filtered_flat_args, captured_inputs=graph_function.captured_inputs) # pylint: disable=protected-access
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
> 3356 call_context_key in self._function_cache.missed):
> 3357 return self._define_function_with_shape_relaxation(
> -> 3358 args, kwargs, flat_args, filtered_flat_args, cache_key_context)
> 3359
> 3360 self._function_cache.missed.add(call_context_key)
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _define_function_with_shape_relaxation(self, args, kwargs, flat_args, filtered_flat_args, cache_key_context)
> 3278
> 3279 graph_function = self._create_graph_function(
> -> 3280 args, kwargs, override_flat_arg_shapes=relaxed_arg_shapes)
> 3281 self._function_cache.arg_relaxed[rank_only_cache_key] = graph_function
> 3282
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
> 3204 arg_names=arg_names,
> 3205 override_flat_arg_shapes=override_flat_arg_shapes,
> -> 3206 capture_by_value=self._capture_by_value),
> 3207 self._function_attributes,
> 3208 function_spec=self.function_spec,
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
> 988 _, original_func = tf_decorator.unwrap(python_func)
> 989
> --> 990 func_outputs = python_func(*func_args, **func_kwargs)
> 991
> 992 # invariant: `func_outputs` contains only Tensors, CompositeTensors,
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
> 632 xla_context.Exit()
> 633 else:
> --> 634 out = weak_wrapped_fn().**wrapped**(*args, **kwds)
> 635 return out
> 636
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
> 975 except Exception as e: # pylint:disable=broad-except
> 976 if hasattr(e, "ag_error_metadata"):
> --> 977 raise e.ag_error_metadata.to_exception(e)
> 978 else:
> 979 raise
> 
> ValueError: in user code:
> 
> ```
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:805 train_function  *
>     return step_function(self, iterator)
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:795 step_function  **
>     outputs = model.distribute_strategy.run(run_step, args=(data,))
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:1259 run
>     return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica
>     return self._call_for_each_replica(fn, args, kwargs)
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica
>     return fn(*args, **kwargs)
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:788 run_step  **
>     outputs = model.train_step(data)
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:754 train_step
>     y_pred = self(x, training=True)
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__
>     input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/input_spec.py:207 assert_input_compatibility
>     ' input tensors. Inputs received: ' + str(inputs))
> 
> ValueError: Layer model_1 expects 2 input(s), but it received 3 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, None) dtype=float32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, None) dtype=int32>, <tf.Tensor 'IteratorGetNext:2' shape=(None, None) dtype=float32>]
> ```

https://colab.research.google.com/drive/1EMV841olelsbeMixPrqO0xYWkoLkPpGR?usp=sharing

**Comment by savya08** [comment]
The issue is due to a difference in the TensorFlow version. When I wrote the code, I used TensorFlow 1.x.

A simple solution will be to add the following line at the top of your colab notebook:
`%tensorflow_version 1.x`

Hope this resolves your issue.

**Comment by E-B-Manohar** [comment]
> %tensorflow_version 1.x

Oh, Great! Working Well.. Thank You
